const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
let envConfig = {};

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split(/\r?\n/).forEach(line => {
    // Ignore comments and empty lines
    if (line && !line.trim().startsWith('#') && line.includes('=')) {
      const parts = line.split('=');
      const key = parts[0].trim();
      const value = parts.slice(1).join('=').trim();
      envConfig[key] = value;
    }
  });
}

const targetDir = path.join(__dirname, 'src', 'environments');
const targetPath = path.join(targetDir, 'environment.ts');

if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

const apiUrl = envConfig.API_URL || process.env.API_URL || 'http://localhost:5000/api';

const envConfigFile = `// This file is auto-generated by set-env.js
export const environment = {
  production: false,
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(targetPath, envConfigFile, 'utf8');
console.log(`Successfully generated environment.ts at ${targetPath}`);
